# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name: DotnetApp-CICD-Test
trigger:
- master

variables:
  buildConfiguration: 'Release'

stages:
  - stage: Build
    pool: Default
    jobs:
      - job: Build

        steps:
        - task: DotNetCoreCLI@2
          inputs:
            command: 'restore'
            projects: '**/CustomerApi.csproj'
            feedsToUse: 'select'
          displayName: Restore
        - task: DotNetCoreCLI@2
          inputs:
            command: 'build'
            projects: '**/CustomerApi.csproj'
          displayName: Build
        - task: DotNetCoreCLI@2
          inputs:
            command: 'test'
            projects: '**/CustomerApi.Test.csproj'
          displayName: Unit Test
        - task: DotNetCoreCLI@2
          inputs:
            command: 'publish'
            publishWebProjects: true
          displayName: Publish
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'RetailApp'
          displayName: Publish Artifact